#+TITLE: LSP 설정
#+AUTHOR: Holy Frege
#+DESCRIPTION: Org-HTML export made simple.
#+KEYWORDS:  org-mode, export, html, theme, style, css, js, bigblow
#+LANGUAGE:  en
#+OPTIONS:   H:4 toc:t num:2  ^:nil
#+MACRO: color @@html:<font color=></font>@@
#+PROPERTY:  header-args :padline no
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+LATEX_HEADER: \usepackage{kotex}
#+latex_header: \hypersetup{colorlinks=true}
* LSP에 관해
#+begin_note
lsp는 server와 client가 있다. emacs의 lsp-mode는 lsp client를 의미한다. server는 programming language별로 있으며, 별도로 system에 설치해야 한다. 설치방법은 M-x lsp-install-server로 쉽게 설치할 수 있다. client가 좀 복잡한데, 보통은 programming language별로 mode에 대한 설정을 한후 hook으로 lsp-mode를 호출하는 방식을 사용한다. 그래서 2개의 설정을 한다. lsp-mode에 대한 설정과 programming-mode에 관한 설정이다. 이 두가지에 대해 살펴볼 것이다.
#+end_note
* LSP client 설치.
- (1) lsp-mode 설정(minimal lsp)
#+begin_note
lsp-mode는 모든 programming language에서 공통적으로 호출할때 사용한다. 여기선  minimal 설정에 대해 알아본다.. 확장 package를 설치하지 않는다. 아래를 참고하자.
- command: lsp-mode를 실행할 방법을 정의한다. lsp로 하던지, lsp-deferred를 할지 선택 가능하다.
- lsp-keymap-prefix:  lsp가 가진 keymap에 prefix를 추가한 것이다. lsp mode에 binding된 key들을 which-key에 통합하는 코드도 있다.
- which-key 통합: which-key는 minibuffer에 보이는 key에 대한 설명이다. 이것을 보여주게 한다.

#+end_note
 #+begin_tip
  (use-package lsp-mode
    :commands lsp lsp-deferred
    :init
    (setq lsp-keymap-prefix "C-c l")
    :config
    (lsp-enable-which-key-integration t)
  )
 #+end_tip
- external lsp
  #+begin_note
  - lsp-ui
    (use-package lsp-ui :commands lsp-ui-mode)
  - lsp-ivy
    (use-package lsp-ivy :commands lsp-ivy-workspace-symbol)
  - lsp-treemacs
    (use-package lsp-treemacs :commands lsp-treemacs-errors-list)
  - dap mode
    ;; (use-package dap-LANGUAGE) to load the dap adapter for your language

  #+end_note

- (2) programming mode 설정
  #+begin_note
  programming language별로 설정한다. 파일을 열때 확장자에 따라 mode가 선택되게 하는 역할과, mode가 선택된 후, lsp를 호출하는 hook을 포함한다. 이렇게 하면 특정 파일을 열었을 때, lsp client로 동작이 된다. 이 부분은 language별로 별도의 setting을 정리할 계획이다.
  #+end_note

* LSP server 설치
#+begin_note
lsp server는 system에 설치한다. 언어별로 설치해야 한다. 가장 쉽게는 M-x lsp-install-server를 사용하는 것이다. https://emacs-lsp.github.io/lsp-mode/  여기에서 menu로 들어가서, language에서 원하는 언어를 선택하면, 설치 방법이 나와 있다.
#+end_note

* LSP에서 자주 사용
#+begin_note
참조리스트, 특정 함수를 참조하는거 lsp-xref-find-references M-?
#+end_note
