#+TITLE: Prolog lsp mode
#+AUTHOR: Holy Frege
#+DESCRIPTION: Org-HTML export made simple.
#+KEYWORDS:  org-mode, export, html, theme, style, css, js, bigblow
#+LANGUAGE:  en
#+OPTIONS:   H:4 toc:t num:2  ^:nil
#+MACRO: color @@html:<font color=></font>@@
#+PROPERTY:  header-args :padline no
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+LATEX_HEADER: \usepackage{kotex}
#+latex_header: \hypersetup{colorlinks=true}
* prolog lsp server
#+begin_note
swipl -g 'pack_install(lsp_server).'
#+end_note
* prolog lsp mode (client)
#+begin_note
prolog의 client설정은 자세하게 나온것을 찾을 수 없었다. typescript하고 비슷하게 설정하려 했으나 잘되지 않았다. 우선 내가 설정한것은 .pl파일을 열거나 만들때 prolog mode로 진입해야 하는데, prolog.el이라는 prolog mode 지원 파일이 elpa or melpa에 있어야 하는데 없었다. 그래서 그냥  아래와 같이 설정했다. lsp mode를 호출하는데 있어서, 문제가 있었다. lsp server에  prolog가 등록되지 않은 언어이기 때문에 등록하는 code를 lsp-mode의 config에 설정해야만 했다. 이렇게 하니 동작은 되었다.
#+end_note
 #+begin_tip
 (load "~/.emacs.d/elpa/prolog.el")
  (add-to-list 'auto-mode-alist '("\\.pl$" . prolog-mode))
  (add-hook 'prolog-mode-hook 'lsp-deferred)
 #+end_tip
- prolog 등록 코드
  #+begin_tip
      (lsp-register-client
     (make-lsp-client
      :new-connection
      (lsp-stdio-connection (list "swipl"
                                 "-g" "use_module(library(lsp_server))."
                                 "-g" "lsp_server:main"
                                 "-t" "halt"
                                 "--" "stdio"))
      :major-modes '(prolog-mode)
      :priority 1
      :multi-root t
      :server-id 'prolog-ls))
  #+end_tip
